on: [push, workflow_dispatch]
jobs:
  ci:
    runs-on: [Windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: |
          Invoke-WebRequest https://www.apple.com/itunes/download/win64 -OutFile ${{ github.workspace }}\iTunes64Setup.exe
          cmd /c '${{ github.workspace }}\makeportable2.cmd'
      - uses: actions/upload-artifact@v4
        with:
          name: CoreAudioLib64
          path: ${{ github.workspace }}/QTfiles64/*

